build.gradle, src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/metricsdb/Dimensions.java, src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/metricsdb/Metric.java, src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/metricsdb/MetricsDB.java, src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/framework/core/MetricsDBProvider.java, src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/samplers/MetricsDBFileSampler.java, src/test/java/com/amazon/opendistro/opensearch/performanceanalyzer/metricsdb/MetricsDBTests.java, src/test/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/samplers/MetricsDBFileSamplerTest.java, src/test/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/spec/MetricsDBProviderTestHelper.java, src/test/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/spec/MetricsDBRcaIntegration.java
Due to global gitignore parameters. Some files with prefix metricsdb* were excluded in the merge.  
Added the missing metricsdb* files …
=> Add missing metricsdb* files and enable spotless

INSTALL.md, build.gradle, docker/Dockerfile, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/core/Util.java
Fix Integration test and update README for beta release …
=> Fix Integration test and update README

.github/workflows/gradle.yml, CODE_OF_CONDUCT.md, INSTALL.md, README.md, build.gradle, docker/Dockerfile, docs/gauntlet.md, src/main/java/org/opensearch/performanceanalyzer/rca/README.md, src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/temperature/README.md, src/main/resources/plugin-descriptor.properties, src/test/java/org/opensearch/performanceanalyzer/rca/integTests/framework/annotations/AMetric.java
Update to rc1 version and opendistro links …
=> Update to rc1 version and opendistro links

.github/workflows/gradle.yml, INSTALL.md
Update upstream dependency and README …
=> Update upstream dependency and README

build.gradle, src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/threadpool/QueueRejectionRca.java
https://github.com/opensearch-project/performance-analyzer-rca/issues/20
Change the log level for logging empty flowunits, this is expected in elected masters. 
Removing the retry. Going forward, when a test fails we need to fix or ignore the tests. 
For more …
=> Change log level and remove retry

build.gradle, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerAppTest.java
https://github.com/opensearch-project/performance-analyzer-rca/issues/20
Add retries for flaky tests and fix failing tests …
=> Add retries for flaky tests and fix failing tests

src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRca.java, src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRcaTest.java
Signed-off-by: Mital Awachat <awachatm@amazon.com>
Pass healthy context explicitly for admission control rca
- [] New functionality has been documented.
- [] New functionality has javadoc added
=> [AdmissionControlRca] Pass healthy context explicitly

.github/workflows/gradle.yml, build.gradle, src/test/java/org/opensearch/performanceanalyzer/reader/MetricsEmitterTests.java
Update branches to 1.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certificate-of- …
=> Update branches to 1.1

build.gradle
Bump commons-io version from 2.3 to 2.7
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/b …
=> Bump commons-io version from 2.3 to 2.7

.github/workflows/gradle.yml
Switch opensearch from 1.x to 1.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/ma …
=> Switch opensearch from 1.x to 1.1

.github/workflows/gradle.yml
Switch opensearch version from 1.x to 1.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#develo …
=> Switch opensearch version from 1.x to 1.1

.github/workflows/gradle.yml, build.gradle
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Change main to 1.2

.github/workflows/gradle.yml, README.md, build.gradle, pa_config/log4j2.xml, src/main/java/org/opensearch/performanceanalyzer/collectors/StatsCollector.java
=> 1.2 release

.github/workflows/gradle.yml
Update branch to 1.2
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTI …
=> Update branch to 1.2

docker/Dockerfile
Update docker artifact link
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyz …
=> Update docker artifact link

.github/workflows/gauntlet-tests-workflow.yml, .github/workflows/gradle.yml, INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
opensearch-project/opensearch-build#1333
Upgrade plugin and log4j version
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/ma …
=> Upgrade plugin and log4j version

.github/workflows/gauntlet-tests-workflow.yml, .github/workflows/gradle.yml, INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
Signed-off-by: dblock <dblock@dblock.org>
Upgrade log4j dependency.
Part of https://github.com/opensearch-project/performance-analyzer-rca/issues/104
=> Upgraded to log4j 2.17 in 1.2

.github/workflows/gauntlet-tests-workflow.yml, .github/workflows/gradle.yml, INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
* Upgraded to log4j 2.17.
Signed-off-by: dblock <dblock@dblock.org>
* Bump version to 1.2.3.
Signed-off-by: dblock <dblock@dblock.org>
For more information on …
=> Upgraded to log4j 2.17 in 1.2 (#105)

.github/workflows/links.yml, .lychee.excludes
Signed-off-by: dblock <dblock@amazon.com>
Fix and lock link checker at lycheeverse/lychee-action@v1.2.0.
=> Fix and lock link checker at lycheeverse/lychee-action@v1.2.0.

INSTALL.md, build.gradle, docker/docker-compose.yml
For more information on following Developer Certificate of Origin and signing off your commits, please …
=> Upgrade docker to 1.3

.github/workflows/gradle.yml, build.gradle, checkstyle/findbugs-exclude.xml
* Upgrade grpc-netty version
* Add classes to exlude in findbugs
* Upgrade protobuf version
Upgrade grpc-netty-shaded, protobuf and guava version 
By submitting this pull …
=> Upgrade grpc-netty-shaded, protobuf and guava version 

.github/workflows/gradle.yml
=> Update the branch to main

THIRD-PARTY, build.gradle
Signed-off-by: David Zane <davizane@amazon.com> …
=> updated jacksonVersion to 2.12.6

.github/workflows/gradle.yml, build.gradle
Upgrade grpc netty and bouncycastle versions …
=> Upgrade grpc netty and bouncycastle versions

.github/workflows/gradle.yml
=> Update the PA branch to main

docker/Dockerfile, pa_bin/performance-analyzer-agent
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Closes https://github.com/opensearch-project/performance-analyzer-rca/issues/127
Add support for OPENSEARCH_JAVA_HOME (see please https://github.com/opensearch-project/OpenSearch/issues/1872), as an alternative to JAVA_HOME (both should work just fine).
N/A
See please https://github.com/opensearch-project/OpenSearch/issues/1872
For more information on following Developer Certificate of Origin and signing off your …
=> [FEATURE] Add support for OPENSEARCH_JAVA_HOME

.github/workflows/gradle.yml, DEVELOPER_GUIDE.md, build.gradle
Merge commits from main into 1.3
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/mai …
=> Merge commits from main into 1.3

.github/workflows/gauntlet-tests-workflow.yml, .github/workflows/gradle.yml, INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
https://github.com/opensearch-project/opensearch-build/issues/1805
=> Bump version to 1.3.1

.gitignore, INSTALL.md, build.gradle, docker/docker-compose.yml, src/main/java/org/opensearch/performanceanalyzer/jvm/ThreadList.java, src/main/resources/plugin-descriptor.properties
Remove setting property in ThreadList …
=> Remove setting property in ThreadList

INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.
=> Change 2.0-alpha1 to 2.0-rc1.

.github/workflows/gradle.yml, build.gradle
Changes for 2.0. Had Cut a branch from main for PA and RCA today. This change updates branches to 2.0.
Related in PA - https://github.com/opensearch-project/performance-analyzer/pull/192
For more information on following Developer Certificate of Origin …
=> Rca 2.0 change

bin/performance-analyzer-agent, docker/Dockerfile, src/main/java/org/opensearch/performanceanalyzer/collectors/StatsCollector.java, src/main/java/org/opensearch/performanceanalyzer/config/PluginSettings.java
=> Merge from main, fix rpm build

INSTALL.md
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
=> Fixing typos in installation documentation

config/opensearch_security.policy
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
#176 
Adding permission to connect/resolve on 9600
=> Adding socket permission to connect,resolve on localhost:9600

INSTALL.md, build.gradle, src/main/resources/plugin-descriptor.properties
https://github.com/opensearch-project/performance-analyzer/issues/210
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob …
=> Remove rc1 (#183)

config/opensearch_security.policy
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
(cherry picked from commit 6ae2bf526d4df27f8232d001bf282136df48a681)
#176 #177
=> Backport/backport 177 to 2.0 

pa_config/opensearch_security.policy
Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>
(cherry picked from commit 6ae2bf526d4df27f8232d001bf282136df48a681)
#176 #177 
=> Backport/backport 177 to 1.3

docker/Dockerfile
=> Remove rc1 from Dockerfile

INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
Signed-off-by: pgodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/opensearch-build/issues/2101
N/A
N/A
https://github.com/opensearch-project/opensearch-build/issues/2101
=> Version Increment to 1.3.3 OpenSearch release

INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 2.0.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/ …
=> Increment version to 2.0.1

.github/workflows/gradle.yml, INSTALL.md, build.gradle, docker/Dockerfile, docker/docker-compose.yml, gradle/wrapper/gradle-wrapper.properties, src/main/resources/plugin-descriptor.properties
Update 2.1 release version
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certificate …
=> Update 2.1 release version

src/main/java/org/opensearch/performanceanalyzer/metrics/AllMetrics.java, src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java, src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java, src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadAnalysis.java, src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetric.java, src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsRca.java, src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsSlidingWindow.java, src/main/java/org/opensearch/performanceanalyzer/reader/MetricsEmitter.java, src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsRcaTest.java, src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsSlidingWindowTest.java
Merge commits from main into 2.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certi …
=> Merge commits from main into 2.1

INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.4.
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Incremented version to 1.3.4.

INSTALL.md, build.gradle, docker/Dockerfile, docker/docker-compose.yml, src/main/java/org/opensearch/performanceanalyzer/core/Util.java, src/main/resources/plugin-descriptor.properties
Signed-off-by: Sagar Upadhyaya <sagar.upadhyaya.121@amazon.com>
Version update to 2.2 - https://github.com/opensearch-project/performance-analyzer/issues/242
And change to not use opendistro legacy url.
For more information on following Developer …
=> Update version to 2.2

build.gradle
Signed-off-by: Sagar Upadhyaya <sagar.upadhyaya.121@amazon.com>
PA branch to 2.2
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyz …
=> Updating PA branch to 2.2

INSTALL.md, build.gradle, docker/Dockerfile, src/main/resources/plugin-descriptor.properties
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348
Incremented version to 1.3.5.
=> [Release 1.3.5] Version increment

build.gradle
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
version increment automation: Update task name.
https://github.com/opensearch-project/performance-analyzer-rca/issues/195
=> Version increment automation: update task name

build.gradle, docker/Dockerfile
Upgrading jackson dependency as per CVE. …
=> Upgrading jackson versions

build.gradle
Jackson version upgrade as per CVE. …
=> Upgrade jackson version

build.gradle, docker/Dockerfile
* Upgrading jackson versions
* Fixing dockerfile typo issue
Upgrading jackson versions (#216)
By submitting this pull request, I confirm that my contribution is made under the …
=> Upgrading jackson versions (#216)

INSTALL.md, build.gradle, docker/Dockerfile, docker/docker-compose.yml, src/main/resources/plugin-descriptor.properties
Update version to 2.3
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca …
=> Update version to 2.3

INSTALL.md, build.gradle, docker/Dockerfile, docker/docker-compose.yml, src/main/resources/plugin-descriptor.properties
Bump version to 2.4
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/b …
=> Bump version to 2.4

.github/workflows/gradle.yml, build.gradle
Changes for 2.3 release.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRI …
=> Changes for opensearch 2.3 release.

.github/workflows/gradle.yml, build.gradle
Modify pa branch to 2.x
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-r …
=> Modify PA branch to 2.x

INSTALL.md, build.gradle, docker/Dockerfile, docker/docker-compose.yml, src/main/resources/plugin-descriptor.properties
Bump main branch version to 3.0 …
=> Bump version to 3.0

.github/workflows/gradle.yml
Signed-off-by: Kiran Prakash <awskiran@amazon.com>
This is reverting changes https://github.com/opensearch-project/performance-analyzer-rca/pull/230 brought in purely for a green build
=> Revert fork and branch related changes in github workflow

build.gradle
Signed-off-by: Kiran Prakash <awskiran@amazon.com>
Update Jackson to 2.13.4 since Open Search core has been.
=> Update Jackson to 2.13.4

build.gradle
Signed-off-by: Kaushal Kumar <kshkmr@amazon.com>
This change is to `protobuf-java and jackson-databind` as we are upgrading these packages in the PA plugin package as well. 
For more information on following Developer Certificate of Origin and signing …
=> upgrade protobuf-java and jackson-databind

build.gradle
Signed-off-by: Kaushal Kumar <kshkmr@amazon.com>
This change is to address the jackson-databind and protobuf-java CVE and backport the existing 1.x versions.
- [] New functionality has javadoc added
For more information on following Developer …
=> upgrade jackson-databind and protobuf-java

build.gradle
This change is to address the [commons-text CVE](https://github.com/opensearch-project/performance-analyzer/issues/306) …
=> upgrade spotbugs plugin minor version to resolve commons-text cve

build.gradle
=> Backport/backport 261 to 2.x

build.gradle
Signed-off-by: Kaushal Kumar <kshkmr@amazon.com>
This pr is to upgrade guava,grpc and protobuf related dependencies. …
=> upgrade grpc,guava and protobuf minor versions

build.gradle, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerWebServerTest.java
Backport for #273
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING. …
=> Backport 273 to 2.x

build.gradle
Signed-off-by: Filip Drobnjakovic <drobnjakovicfilip@gmail.com>
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Backport 270 to 2.x

build.gradle
Fix for failing OS 1.3.9 release build
=> Upgrade jackson to 2.14.2

src/test/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotShardSummaryTest.java, src/test/java/org/opensearch/performanceanalyzer/rca/store/ResourceHeatMapGraphTest.java, src/test/java/org/opensearch/performanceanalyzer/store/rca/hotshard/HotShardClusterRcaTest.java, src/test/java/org/opensearch/performanceanalyzer/store/rca/hotshard/HotShardRcaTest.java, src/test/resources/rca/rca_elected_cluster_manager.conf
Test adjustment followup for #295. Test and comments are refitted to match the re-implementation but the test threshold values are likely to change in future global threshold tuning followups. 
For more information on …
=> Test adjustments to match re-implementation of Hot Shard RCA.

.github/CODEOWNERS, MAINTAINERS.md
**Description**: Baseline repo MAINTAINERS, CODEOWNERS groups
**Issues Resolved**
Fixes https://github.com/opensearch-project/performance-analyzer-rca/issues/293
=> Baseline repo MAINTAINERS, CODEOWNERS groups

build.gradle
Make dependencies match ones on core build-tools library. …
=> Match dependencies with their core versions

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java, src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java, src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java, src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/WriterMetrics.java, src/main/java/org/opensearch/performanceanalyzer/reader/ReaderMetricsProcessor.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerAppTest.java, src/test/java/org/opensearch/performanceanalyzer/reader/ReaderMetricsProcessorTests.java
Add new MeasurementSet metrics. Remove unused ones. Add update stats call where missing.
Implementation of adjustments to MeasurementSets discussed in #311.
=> Update MeasurementSet types and usage

.github/CODEOWNERS, MAINTAINERS.md
[Updating the MAINTAINERS list](https://github.com/opensearch-project/performance-analyzer-rca/commit/51755728adce4289d47a5d9189c42da5efce565c), in-sync with https://github.com/opensearch-project/performance-analyzer-rca/blob/main/.github/CODEOWNERS …
=> Update MAINTAINERS list 

.github/workflows/gradle.yml, build.gradle, docker/Dockerfile
Manually back porting to 2.x branch: https://github.com/opensearch-project/performance-analyzer-rca/pull/276
[A clear and concise description of what you want to happen.](https://github.com/opensearch-project/performance-analyzer-rca/issues/162)
For more information on following Developer Certificate of Origin …
=> [Backport 2.x] Run docker OS cluster with different JDK version

INSTALL.md, build.gradle, docker/docker-compose.yml
=> [Backport 2.x] Update dependencies to the defined ones.

INSTALL.md, build.gradle
Updating the build.gradle and Install for the release
[A clear and concise description of what you want to happen.](https://github.com/opensearch-project/performance-analyzer/issues/415) …
=> [2.7] Updating the build.gradle and Install for the release

build.gradle
=> Update dependencies to the defined ones.

src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java, src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/WriterMetrics.java, src/main/java/org/opensearch/performanceanalyzer/reader/NodeMetricsEventProcessor.java
https://github.com/opensearch-project/performance-analyzer-rca/issues/363
Adding JSON_PARSER_ERROR and CONFIG_OVERRIDES_SER_FAILED
=> Adding JSON_PARSER_ERROR and CONFIG_OVERRIDES_SER_FAILED

.github/workflows/gradle.yml, src/main/resources/plugin-descriptor.properties
[2.8] Updating the gradle.yml and plugin-descriptor.properties
=> [2.8] Updating the gradle.yml and plugin-descriptor.properties

src/main/java/org/opensearch/performanceanalyzer/rca/Version.java
// Bumping this post the Commons Lib(https://github.com/opensearch-project/performance-analyzer-commons/issues/2)
// and Service Metrics(https://github.com/opensearch-project/performance-analyzer-commons/issues/8) change
=> Update RCA Major Version

src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/Symptom.java
Remove dummy log message - added for testing
=> Remove dummy log message

build.gradle
https://github.com/opensearch-project/performance-analyzer-rca/issues/435
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/ …
=> [CVE-2023-33201] Upgrade bcprov to bcprov-jdk15to18

build.gradle
fix CVE-2023-33201
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certificate-of-orig …
=> [CVE-2023-33201] Upgrade bcpkix to bcpkix-jdk15to18

src/main/java/org/opensearch/performanceanalyzer/rca/RcaController.java, src/test/java/org/opensearch/performanceanalyzer/rest/QueryRcaRequestHandlerTest.java, src/test/resources/rca/rca_query_muted_test.conf, src/test/resources/rca/rca_query_test.conf
=> REST layer UT's for QueryRcaRequestHandler

INSTALL.md, build.gradle
Add changes for RCA 2.9 branch
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-certifi …
=> Changes for 2.9 release

docker/docker-compose.yml
Update docker compose file to use version number 2.9
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTIN …
=> update docker compose file to version 2.9

build.gradle
=> [CVE-2023] fix multiple cve issues

INSTALL.md, build.gradle, docker/docker-compose.yml, src/main/java/org/opensearch/performanceanalyzer/rca/Version.java, src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java
=> Add changes for release v2.10

build.gradle
Update performance-analyzer-commons version
=> Update performance-analyzer-commons version

.github/CODEOWNERS, MAINTAINERS.md
Add @arjunkumargiri as repo maintainer
=> Add @arjunkumargiri as repo maintainer

INSTALL.md, README.md, build.gradle
[https://github.com/opensearch-project/performance-analyzer-rca/issues/489](https://github.com/opensearch-project/performance-analyzer-rca/issues/489)
Updating the build.gradle and Install for 2.11 release
=> [2.11] Updating the build.gradle and Install for the release

INSTALL.md, README.md, build.gradle, docker/docker-compose.yml
Signed-off-by: Arjun kumar Giri <arjung@amazon.com>
Update docker and gradle for release
=> [2.11] Update docker and gradle for launch

build.gradle
Update performance-analyzer-commons to use the tag 1.3.0
=> Upgrade pa-commons version

.github/CODEOWNERS, MAINTAINERS.md, build.gradle
1. Add new Contributors to the repo
2. Bump Commons library version
=> Add new maintainers to repo

build.gradle
https://github.com/opensearch-project/performance-analyzer/issues/663#issuecomment-2161311887 …
=> Bump PA-RCA to use 1.4.0 PA commons lib

build.gradle
Bumping bouncycastle to v1.78. …
=> Bumping bouncycastle to v1.78.1

build.gradle
=> Bump PA commons to 1.5.0

build.gradle
bump up PA commons to 1.6
NA
NA
NA
=> bump up PA commons to 1.6

.github/workflows/gradle.yml, build.gradle
bump commons-io to 2.140.
- [] New functionality includes testing.
- [] New functionality has javadoc added
For more information on following Developer …
=> bump commons-io to 2.140.
