opensearch-project/performance-analyzer-rca

.github/workflows/gradle.yml
build.gradle
docker/Dockerfile
docker/docker-entrypoint.sh
gradle/wrapper/gradle-wrapper.properties

Update version to 1.0 beta
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyze …

Update version to 1.0 beta

---

.github/workflows/gradle.yml
build.gradle
docker/Dockerfile

Update docker artifact link
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyz …

Update docker artifact link

---

src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/PerformanceAnalyzerWebServer.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/metrics/handler/MetricsServerHandler.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/net/GRPCConnectionManager.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/RcaController.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/RcaControllerHelper.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/framework/api/Metric.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/framework/api/Symptom.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/net/handler/PublishRequestHandler.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/stats/emitters/PeriodicSamplers.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/rca/stats/eval/impl/NamedCounter.java
src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/reader_writer_shared/EventLogFileHandler.java

Modify print stacktrace to logger instead of stdout …

Modify printing stacktrace to logger instead of stdout

---

src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/collectors/StatExceptionCode.java

Signoff by: Harold Xiao haoruxia@amazon.com
Adding a new stat exception type for config directory not found. The exception is called in [this PR: ](https://github.com/opensearch-project/performance-analyzer/pull/9/files) 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CO …

Add CONFIG_DIR_NOT_FOUND in StatExceptionCode

---

src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/decisionmaker/deciders/jvm/JvmGenTuningPolicy.java
src/test/java/com/amazon/opendistro/opensearch/performanceanalyzer/decisionmaker/deciders/jvm/JvmGenTuningPolicyTest.java

Signoff By: Harold Xiao haoruxia@amazon.com
Modify the JVM gen tuning policy -> computeIncrease function to prevent increasing young gen size if the ratio is not beyond 3:1. Update the Unit test.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-ce …

Modify JVM gen tuning policy and update the Unit test

---

build.gradle

Upgrading Jackson version to match OpenSearch core and to address CVE.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28491

Upgrade Jackson version to 2.11.4

---

INSTALL.md
README.md
build.gradle
docs/batch-metrics-api.md
src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java
src/main/java/org/opensearch/performanceanalyzer/core/Util.java
src/main/java/org/opensearch/performanceanalyzer/rest/QueryActionRequestHandler.java
src/main/java/org/opensearch/performanceanalyzer/rest/QueryBatchRequestHandler.java
src/main/java/org/opensearch/performanceanalyzer/rest/QueryRcaRequestHandler.java
src/test/java/org/opensearch/performanceanalyzer/rest/QueryBatchRequestHandlerTest.java

Updating calls to the Performance Analyzer plugin API to follow the new `/_plugins` naming convention.
RCA behavior should be unchanged.
This is a required change to follow new OpenSearch guidelines.
https://github.com/opensearch-project/opensearch-plugins/blob/main/UPGRADING.md#settings-backwards-compatibility …

Replace references to /_opendistro with /_plugins

---

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java

We want the Performance Analyzer agent API for OpenSearch to be backward compatible with OpenDistro.
Adding HttpContexts that will resolve the old `/_opendistro` resource name.

Create HTTP contexts for legacy resource name

---

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java
src/main/java/org/opensearch/performanceanalyzer/core/Util.java
src/main/java/org/opensearch/performanceanalyzer/rca/RcaController.java

Signed-off-by: Joshua Tokle <joshtok@amazon.com>
The previous backward compatibility PR (#18) didn't update RcaController. 
Add backward compatibility to resources defined in RcaController.
```
[root@7616e7370051 opensearch]# curl http://localhost:9600/_opendistro/_performanceanalyzer/rca -XGET
{"OldGenReclamationRca":[{"rca_name":"OldGenReclamationRca","timestamp":1621960502692,"state":"unknown"}],"HighOldGenOccupancyRca":[{"rca_name":"HighOldGenOccupancyRca","timestamp":1621960502693,"state":"healthy"}],"QueueRejectionRca":[{"rca_name":"QueueRejectionRca","timestamp":1621960457976,"state":"healthy"}],"FieldDataCacheRca":[{"rca_name":"FieldDataCac …
```

Add backward compatible resource names to RcaController

---

.github/workflows/gradle.yml
INSTALL.md
build.gradle
docker/Dockerfile
src/main/resources/plugin-descriptor.properties

Update version from 1.0.0.0-rc1 to 1.0.0.0
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rc …

Update version from 1.0.0.0-rc1 to 1.0.0.0

---

docker/Dockerfile

Update docker artifact to track latest
```
> Task :integTest
org.opensearch.performanceanalyzer.integ_test.HeapMetricsIT > checkHeapInit STANDARD_OUT
[2021-07-01T20:45:07,819][INFO ][o.o.p.i.HeapMetricsIT    ] [checkHeapInit] before test
[2021-07-01T20:45:08,186][INFO ][o.o.p.i.HeapMetricsIT    ] [checkHeapInit] initializing REST clients against …
```

Update docker artifact to track latest

---

src/main/java/org/opensearch/performanceanalyzer/reader_writer_shared/EventLogFileHandler.java

Addressing the spotbug failure. Handling the Null condition for `File.list()`
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer- …

Addressing the spotbug failure

---

src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/RcaGraphMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/cache/FieldDataCacheRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/cache/ShardRequestCacheRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/threadpool/QueueRejectionRca.java
src/test/java/org/opensearch/performanceanalyzer/rca/framework/api/metrics/MetricTestHelper.java
src/test/java/org/opensearch/performanceanalyzer/store/rca/cache/FieldDataCacheRcaTest.java
src/test/java/org/opensearch/performanceanalyzer/store/rca/cache/ShardRequestCacheRcaTest.java
src/test/java/org/opensearch/performanceanalyzer/store/rca/threadpool/QueueRejectionRcaTest.java

**Is your feature request related to a problem? Please provide an existing Issue https://github.com/opensearch-project/performance-analyzer-rca/issues/33
[RCA] Handle Empty FU within Cache and Queue RCAs
In this case, PA was unable to persist value for 64 metric for the one hour window and thus, RCA was running into Cache_Request_Hit metric table does not exist. Returning null for the metric/dimension and QueryMetric was returning empty Flow units to ShardRequestCacheRCA. The ShardRequestCacheRCA on finding an empty FU, [ignores it](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/cache/ShardRequestCacheRca.java#L240). This was done to accommodate any delays in metric persistence from PA. 
Before this …

Handling empty flow unit during Cache/Queue RCA execution

---

src/main/java/org/opensearch/performanceanalyzer/rca/RcaController.java
src/test/java/org/opensearch/performanceanalyzer/rca/RcaControllerTest.java
src/test/java/org/opensearch/performanceanalyzer/rca/RcaTestHelper.java
src/test/java/org/opensearch/performanceanalyzer/rca/listener/MisbehavingGraphOperateMethodListenerTest.java

`RCA_FRAMEWORK_CRASH` metric should be emitted when the top level controller thread crashes
The metric is already present [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java#L36) but we never emit this metric.
For more …

Adding metric emission + UT for RCA_FRAMEWORK_CRASH

---

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java
src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerThreads.java
src/main/java/org/opensearch/performanceanalyzer/collectors/ScheduledMetricCollectorsExecutor.java
src/main/java/org/opensearch/performanceanalyzer/collectors/StatExceptionCode.java
src/main/java/org/opensearch/performanceanalyzer/collectors/StatsCollector.java
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/deciders/jvm/sizing/HeapSizeIncreasePolicy.java
src/main/java/org/opensearch/performanceanalyzer/jvm/ThreadList.java
src/main/java/org/opensearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/RcaController.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/core/RcaConf.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/RcaGraphMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/RcaRuntimeMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/RcaVerticesMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/WriterMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/util/RcaConsts.java
src/main/java/org/opensearch/performanceanalyzer/rca/net/tasks/FlowUnitRxTask.java
src/main/java/org/opensearch/performanceanalyzer/rca/net/tasks/FlowUnitTxTask.java
src/main/java/org/opensearch/performanceanalyzer/rca/stats/RcaStatsReporter.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hotshard/HotShardRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/jvmsizing/HighOldGenOccupancyRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/jvmsizing/OldGenContendedRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/jvmsizing/OldGenReclamationRca.java
src/main/java/org/opensearch/performanceanalyzer/reader/ReaderMetricsProcessor.java
src/main/java/org/opensearch/performanceanalyzer/threads/ThreadProvider.java
src/main/java/org/opensearch/performanceanalyzer/threads/exceptions/PAThreadException.java
src/main/java/org/opensearch/performanceanalyzer/util/FileHelper.java
src/test/java/org/opensearch/performanceanalyzer/jvm/ThreadListTest.java

`StatsCollector` is used by RCA-Agent and PerformanceAnalyzer Plugin to publish service metrics. We run this collector through `ScheduledMetricCollectorsExecutor` and the executor can mark the collector as SLOW and subsequently MUTED if the collector is slow. A muted collector doesn't emit any metrics and thus we can end up missing the helpful service metrics.
This PR contains changes to skip muting for  `StatsCollector` and re-factoring to move away from `StatExceptionCode` to Metric Aggregators. 
Adding more granular code change details:
* PerformanceAnalyzerApp.java : Removing Default Exception code. (Moving to Aggregator metric framework, does not require default codes)
* …

Addressing changes for StatsCollector

---

pa_bin/performance-analyzer-agent

Recent OOM/swapping issues
As one of the best practices, it is recommended that all JVM processes run with the flag -XX:+ExitOnOutOfMemoryError

Fix for OOM error

---

src/main/java/org/opensearch/performanceanalyzer/reader/ReaderMetricsProcessor.java

Signed-off-by: Marc Handalian <handalm@amazon.com>
This PR fixes the build of main by fixing spotbugs to pass.
[This](https://github.com/opensearch-project/performance-analyzer-rca/commit/e03a8fb5504d8cda8a09da8b2248498b78795da3#diff-5c0956a1db407ce2ae60579e09c90a72a48845dbc91a5330ec3dd9394f19275c) commit removed the usage of this variable but left its declaration, causing spotbugs to fail.
Remove unused variable.  Without this change the following fails on main:
```
./gradlew build -x test
```
This is further causing problems because the performance-analyzer plugin repo always clones and builds main.
closes #46 
- [ x] Commits are signed per the …

Fix spotbugs failure by removing unused variable.

---

src/main/java/org/opensearch/performanceanalyzer/reader_writer_shared/EventLogFileHandler.java

https://github.com/opensearch-project/performance-analyzer-rca/issues/38
Calling the delete methods with privilege. 
Tested by spinning up a docker and confirmed that files are cleaned as expected.

Add privileges for removing files

---

build.gradle
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/WriterMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/threadpool/QueueRejectionRca.java

This change is a part of the refactoring stats collector change. Adding a writer metric that performance analyzer plugin will use for emitting metric denoting if the master node is up or not. 
For more information on …

Add master not up writer metric 

---

build.gradle

This PR removes the need for the main branch to be checked out
in order to build.
Signed-off-by: Marc Handalian <handalm@amazon.com>
closes #53 
- [ x] Commits are signed per the DCO using --signoff

Remove dependency on main branch when running spotless check.

---

.github/workflows/gradle.yml
INSTALL.md
build.gradle
docker/Dockerfile
docker/docker-compose.yml

Signed-off-by: dblock <dblock@amazon.com>
- Upgrades version to 1.1, uses OpenSearch version.
- Runs snapshot builds by default. 
- Renames output artifact to include version.
- Disables slow tests (see #57)
- Removes ODFE from docker container.
Closes #48, #56, #40.
There's a circular dependency described in https://github.com/opensearch-project/performance-analyzer/issues/50, so https://github.com/opensearch-project/performance-analyzer/pull/53 is needed. Once this is merged I'll switch references to my fork that contains this code.
For more information on following Developer …

Fix snapshot build, upgrade to OpenSearch 1.1.

---

.github/workflows/gradle.yml

Signed-off-by: dblock <dblock@amazon.com>
Now that https://github.com/opensearch-project/performance-analyzer/pull/53 has been merged, use the main branch thereof.
Together with #55, closes #40, closes #56.

Use performance-analyzer main branch.

---

src/main/java/org/opensearch/performanceanalyzer/reader/MetricsEmitter.java
src/test/java/org/opensearch/performanceanalyzer/reader/MetricsEmitterTests.java
src/test/resources/reader/1566413960000
src/test/resources/reader/1566413965000
src/test/resources/reader/1566413970000

#41 
#66 
- The transport thread names are now a regex containing the string `transport_worker`. 
We replace the older and now defunct thread names and `transport_client_boss` and `transport_server_worker` and their corresponding values for Operation dimension in PA metrics API
- The search and write/bulk thread names are currently being ignored and not being categorised as values in the Operation dimension. Added the same
**Testing Output**
`% curl "http://localhost:9600/_plugins/_performanceanalyzer/metrics?metrics=Thread_Blocked_Time&dim=Operation&agg=avg" `
`{"V72-8JqfRHKlMxUGO-HzBw": {"timestamp": 1630517885000, "data": …

Fix thread name categorizations for Operation dimension in metrics API

---

.github/workflows/gauntlet-tests-workflow.yml
build.gradle
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/actions/AdmissionControlAction.java
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/deciders/AdmissionControlDecider.java
src/main/java/org/opensearch/performanceanalyzer/rca/configs/AdmissionControlRcaConfig.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/flow_units/ResourceFlowUnit.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/RcaVerticesMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlClusterRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRca.java
src/main/java/org/opensearch/performanceanalyzer/util/range/Range.java
src/main/java/org/opensearch/performanceanalyzer/util/range/RangeConfiguration.java
src/main/java/org/opensearch/performanceanalyzer/util/range/RequestSizeHeapRangeConfiguration.java
src/test/java/org/opensearch/performanceanalyzer/decisionmaker/actions/AdmissionControlActionTest.java
src/test/java/org/opensearch/performanceanalyzer/decisionmaker/deciders/AdmissionControlDeciderTest.java
src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRcaTest.java

https://github.com/opensearch-project/performance-analyzer-rca/issues/57
https://github.com/opensearch-project/performance-analyzer-rca/issues/65
Add workflow for gauntlet tests and fix spotbug errors …

Add workflow for gauntlet tests and fix spotbug errors

---

src/main/java/org/opensearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/test/java/org/opensearch/performanceanalyzer/reader/MetricsEmitterTests.java

There is an increase in cardinality of metrics due to a recently added metric ```MetricsWriteError``` which always has unique dimension value for field Instance as it includes timestamp and the threadId. This value was emitted continuously due a known bug causing the pa.plugin.stats file to grow really large. This bug is currently fixed in ```1.1```
Alter to remove emitting the entry key with the ```METRICS_WRITE_ERROR``` metric. 
Add any …

Remove emitting the entry key with the METRICS_WRITE_ERROR metric

---

build.gradle
src/main/java/org/opensearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/test/java/org/opensearch/performanceanalyzer/reader/MetricsEmitterTests.java

Bump commons-io version from 2.3 to 2.7
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/b …

Bump commons-io version from 2.3 to 2.7

---

pa_config/rca.conf
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/actions/AdmissionControlAction.java
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/deciders/AdmissionControlDecider.java
src/main/java/org/opensearch/performanceanalyzer/rca/configs/AdmissionControlRcaConfig.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByHeapFactory.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByLargeHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByMediumHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlBySmallHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/model/HeapMetric.java
src/main/java/org/opensearch/performanceanalyzer/util/range/Range.java
src/main/java/org/opensearch/performanceanalyzer/util/range/RequestSizeHeapRangeConfiguration.java
src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRcaTest.java
src/test/java/org/opensearch/performanceanalyzer/reader/MetricsEmitterTests.java
src/test/resources/rca/rca.conf

Signed-off-by: Mital Awachat <awachatm@amazon.com>
* Split admission control rca into SmallHeap / MediumHeap / LargeHeap rca.
* Reduce number of buckets for default configuration request-size controller heap-range to reduce too many auto-tunes for  small percentage of heap variation.

AdmissionControl Split RCA

---

build.gradle
pa_config/rca.conf
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/actions/AdmissionControlAction.java
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/deciders/AdmissionControlDecider.java
src/main/java/org/opensearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/configs/AdmissionControlRcaConfig.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByHeapFactory.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByLargeHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlByMediumHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/heap/AdmissionControlBySmallHeap.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/model/HeapMetric.java
src/main/java/org/opensearch/performanceanalyzer/util/range/Range.java
src/main/java/org/opensearch/performanceanalyzer/util/range/RequestSizeHeapRangeConfiguration.java
src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/admissioncontrol/AdmissionControlRcaTest.java
src/test/java/org/opensearch/performanceanalyzer/reader/MetricsEmitterTests.java
src/test/resources/rca/rca.conf

main to 1.1

---

pa_config/log4j2.xml
src/main/java/org/opensearch/performanceanalyzer/collectors/StatsCollector.java

https://github.com/opensearch-project/performance-analyzer/issues/80
#84
Rotate PerformanceAnalyzer.log and performance_analyzer_agent_stats.log files to avoid disk issue. Set the log level to debug (and not info) for the stats logs to prevent excessive noisy logs being piped to the console and opensearch.log file.
By submitting this pull request, I confirm that my …

Add log rotation and prevent noisy logs

---

.github/workflows/gauntlet-tests-workflow.yml
.github/workflows/gradle.yml
build.gradle
docker/Dockerfile

Upgrade plugin to 1.2.1 version and log4j to 2.15.0 version. …

Upgrade plugin and log4j version

---

.github/workflows/gauntlet-tests-workflow.yml
.github/workflows/gradle.yml
INSTALL.md
build.gradle
docker/Dockerfile
src/main/resources/plugin-descriptor.properties

#110 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTR …

Upgrade plugin version to 1.2.4 and log4j to 2.17.1

---

.github/workflows/gauntlet-tests-workflow.yml
.github/workflows/gradle.yml
INSTALL.md
build.gradle
docker/Dockerfile
src/main/resources/plugin-descriptor.properties

For more information on following Developer Certificate of Origin and signing off your commits, please …

Upgrade plugin to 1.3.0 and log4j to 2.17.1

---

build.gradle

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
The `InitialBootClassLoaderMetaspaceSize` JVM command line flag has been deprecated in JDK-15 [1] and removed in JDK-16 [2]. 
[1] https://bugs.openjdk.java.net/browse/JDK-8242426 
[2] https://bugs.openjdk.java.net/browse/JDK-8221173
Related to https://github.com/opensearch-project/opensearch-build/issues/1523
Drop `InitialBootClassLoaderMetaspaceSize` usage
Make the command line logic dependent on JVM version being used
Closes https://github.com/opensearch-project/performance-analyzer-rca/issues/117
By submitting this pull …

Removing deprecated InitialBootClassLoaderMetaspaceSize JVM command line flag

---

.github/workflows/gradle.yml
build.gradle
checkstyle/findbugs-exclude.xml

Upgrade grpc-netty version to ```1.42.2``` - which upgrades netty-codec to ```4.1.63.Final```
For more information on following Developer Certificate of Origin and …

Upgrade grpc-netty version to 1.42.2

---

.github/workflows/gradle.yml
build.gradle
checkstyle/findbugs-exclude.xml

This reverts commit eeafdf53db74197921c5c88f62efddac0a46e775.
The version upgrade has been merged to ```main``` and reverting this commit as 1.2.4 is released.
For …

Revert "Upgrade grpc-netty version to 1.42.2 (#115)"

---

build.gradle

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
The build of `performance-analyzer` fails with:
```
Execution failed for task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
> Conflict(s) found for the following module(s):
- org.bouncycastle:bcprov-jdk15on between versions 1.70 and 1.68
- org.bouncycastle:bcpkix-jdk15on between versions 1.70 and 1.68
Run with:
--scan or
:dependencyInsight --configuration compileClasspath --dependency org.bouncycastle:bcprov-jdk15on
to get more insight on how to solve the conflict.
```
Updating Bouncycastle to 1.70 since it was updated in  `core` [1] and …

Update Bouncycastle to 1.70

---

src/main/java/org/opensearch/performanceanalyzer/rca/net/handler/PublishRequestHandler.java
src/test/java/org/opensearch/performanceanalyzer/rca/net/handler/PublishRequestHandlerTest.java

https://github.com/opensearch-project/performance-analyzer-rca/issues/131
- Keeps track of which streams were already completed by client via a flag "isCompleted". When RCA is disabled, publisher(active master) checks whether this response stream was already completed. If it was completed, it doesn't invoke onNext on response stream to convey it is shutting down.
Add any other context or screenshots about the feature request …

Fixes RCA crash on active master (#131)

---

.github/workflows/backport.yml
.github/workflows/delete_backport_branch.yml
DEVELOPER_GUIDE.md

Signed-off-by: David Zane <davizane@amazon.com>
Adds backport workflow to allow automatic backport PR creation as we merge to main or label PR. Explanation of script added to documentation.
* We can label previously closed PRs and the action will run.
* As of right now we have to manually delete the branch that the bot creates. This could be changed in the future to be automatic.
resolves https://github.com/opensearch-project/performance-analyzer-rca/issues/93
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certifica …

Add auto backport functionality, backport delete, and documentation

---

build.gradle

While building PA and running unit tests [here](https://github.com/opensearch-project/performance-analyzer/pull/159) for jdk8, workflow step failed as we have a logic currently in build.gradle to export a module which is not supported for versions <=8.
Adding a check.
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Adding check to avoid adding module export for jdk8

---

.github/workflows/gradle.yml
DEVELOPER_GUIDE.md
build.gradle

1. Adding CI matrix for JDK 8, 11 and 14 in CI workflow
2. Updating developer guide to use JDK 11
Solves: https://github.com/opensearch-project/performance-analyzer/issues/91 …

Add CI matrix for jdk 8, 11 and 14

---

src/main/java/org/opensearch/performanceanalyzer/jvm/ThreadList.java

While testing JDK 17 with OS 1.3.0 version earlier, we saw PA resulting into exception([here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/jvm/ThreadList.java#L185)) as JDK 17 had breaking changes where we couldn't type cast into jdk internal classes during runtime. To fix this, desired module is being added with open access for now.
Adding open access to desired module to allow to proceed with runtime access to jdk internal class. 
- Adding "add-export" in …

Exporting module to fix PA JDK 17 runtime issue

---

.github/workflows/gauntlet-tests-workflow.yml
.github/workflows/gradle.yml
DEVELOPER_GUIDE.md
build.gradle
docker/Dockerfile
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/deciders/jvm/JvmGenTuningPolicy.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotClusterSummary.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotNodeSummary.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotResourceSummary.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotShardSummary.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/TopConsumerSummary.java
src/main/java/org/opensearch/performanceanalyzer/rca/response/RcaResponse.java
src/test/java/org/opensearch/performanceanalyzer/rca/response/RcaResponseTest.java

- https://github.com/opensearch-project/performance-analyzer-rca/issues/151
- https://github.com/opensearch-project/performance-analyzer-rca/issues/142
- https://github.com/opensearch-project/performance-analyzer-rca/issues/141
- OS 2.0 related CR where this was taken - https://github.com/opensearch-project/performance-analyzer-rca/pull/152
Add any other context or …

Changes to add jdk17, remove jdk 8,14, OS 2.0 and upgrade to gradle 7

---

pa_config/opensearch_security.policy

Signed-off-by: Surya Sashank Nistala <snistala@amazon.com>
Adds management permission (control) in security policy file to enable/disable thread contention monitoring

Adds management permission (control) in security policy file

---

INSTALL.md
README.md
docker/Dockerfile
src/main/java/org/opensearch/performanceanalyzer/config/PluginSettings.java

https://github.com/opensearch-project/performance-analyzer/issues/188
Update PA directories from plugins to root …

Update PA directories from plugins to root

---

bin/performance-analyzer-agent
docker/Dockerfile
src/main/java/org/opensearch/performanceanalyzer/collectors/StatsCollector.java
src/main/java/org/opensearch/performanceanalyzer/config/PluginSettings.java

https://github.com/opensearch-project/performance-analyzer/issues/197
Checks for ```opensearch.path.conf``` before setting the default config value. 

Fix rpm build by adding config to env variable

---

src/main/java/org/opensearch/performanceanalyzer/config/PluginSettings.java

Disable plugin if configFilePath is not present
Disable plugin if configFilePath is not present …

Disable plugin if configFilePath is not present

---

.github/workflows/gauntlet-tests-workflow.yml
.github/workflows/gradle.yml
build.gradle
src/main/resources/plugin-descriptor.properties

Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.

Incremented version to 1.3.2.

---

src/main/java/org/opensearch/performanceanalyzer/metrics/AllMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadAnalysis.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetric.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsSlidingWindow.java
src/main/java/org/opensearch/performanceanalyzer/reader/MetricsEmitter.java
src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsRcaTest.java
src/test/java/org/opensearch/performanceanalyzer/rca/store/rca/hot_node/ThreadMetricsSlidingWindowTest.java

Adds an RCA which analyses thread blocked time value in the past 60 second window and publisher reader Metric stats for high thread blocked, waited time and count of threads blocked, waited longer than threshold in the past minute.

Thread Metrics RCA.

---

INSTALL.md
build.gradle
docker/Dockerfile
docker/docker-compose.yml
gradle/wrapper/gradle-wrapper.properties
src/main/resources/plugin-descriptor.properties

Update 2.1 release version
https://github.com/opensearch-project/performance-analyzer/issues/231 …

Update 2.1 release version

---

.github/workflows/gradle.yml
build.gradle

Signed-off-by: Kiran Prakash <awskiran@amazon.com>
netty had a [CVE-2022-24823](https://nvd.nist.gov/vuln/detail/CVE-2022-24823) that was patched in [4.1.77.Final](https://github.com/netty/netty/security/advisories/GHSA-269q-hmxg-m83q)
PA RCA uses netty via grpc which updated the netty to 4.1.77.Final in [1.49.0](https://github.com/grpc/grpc-java/commit/7bd079749667df9b39ae39f410c15a1117c447ad)
**For a green build** - This is building off Performance Analyzer against my 
fork - kiranprakash154/performance-analyzer 
branch - kiranprakash154:kp/update-netty-json
**Next Steps:** 
1. Merge this PR
2. Rebase [the PR](https://github.com/opensearch-project/performance-analyzer/pull/273) in …

Update Libraries to fetch the updated netty patched with CVE-2022-24823

---

build.gradle

Signed-off-by: Kiran Prakash <awskiran@amazon.com>
(cherry picked from commit 93c22e74e04c1ba635af7941a41b011beb3d15bf)
Backporting https://github.com/opensearch-project/performance-analyzer-rca/pull/230 but not referring to personal fork and branch.

[Backport] Update grpc to 1.49.0 and gson to 2.9.0

---

docker/docker-compose.yml

Signed-off-by: Kaushal Kumar <kshkmr@amazon.com>
This change is to revert the env var `node.clusterManager` as that will not let the docker container to spin up.
For more information on following Developer Certificate of Origin and signing off your …

revert docker-compose.yml env var change

---

build.gradle

Signed-off-by: Craig Perkins <cwperx@amazon.com>
Updates jackson and jackson-databind to 2.14.1 and netty to 4.1.84.Final to match version from core's version.properties.
Related distribution build failure: https://github.com/opensearch-project/performance-analyzer/issues/337
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

[1.3] Update jackson to 2.14.1 and netty to 4.1.84.Final

---

build.gradle

Netty upgrade fixes https://github.com/opensearch-project/performance-analyzer-rca/issues/260. Guava already on 30.1
Jackson upgrade related to https://github.com/opensearch-project/performance-analyzer-rca/issues/257
Update jackson to 2.14.1 & netty to 4.1.86

Jackson 2.14.1 & netty 4.1.86 upgrades

---

build.gradle

Signed-off-by: Filip Drobnjakovic <drobnjakovicfilip@gmail.com>
#264 
According to https://github.com/spotbugs/spotbugs/discussions/2251 this bcel vulnerability doesn't affect SpotBugs. As there's no tentative date for a new SpotBugs release that would include the version bump from their side and as confirmed by some users from the mentioned issue, pinning the dependency by ourselves gets rid of the warning and doesn't break SpotBugs. As bcel is transitive dependency of a plugin, it has to be done with iterative dependency substitution.
Alternative would be to completely ignore warning as there's no real …

Pin bcel version to 6.6.1

---

build.gradle

This change forces the usage of netty 4.1.86.Final. grpc-netty 1.5.1 depends on the vuln versions, we were overriding the version for some of the included netty jars but not all.
Signed-off-by: Marc Handalian <handalm@amazon.com>
No 4.1.79.Final jars included in lib.
Without this change:
```
./performance-analyzer-rca/lib/netty-common-4.1.86.Final.jar
./performance-analyzer-rca/lib/netty-transport-4.1.86.Final.jar
./performance-analyzer-rca/lib/netty-codec-http-4.1.77.Final.jar …
```

Fix netty dependency to not include vulnerable 4.1.79 version jars.

---

build.gradle
src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerWebServerTest.java

Signed-off-by: Filip Drobnjakovic <drobnjakovicfilip@gmail.com>
Issue #167
Implementation of the proposed solution from the issue (#167) comment (by me). Please raise any additional concerns.

Fix and include unauthenticated user web server test

---

src/main/java/org/opensearch/performanceanalyzer/jvm/HeapMetrics.java
src/test/java/org/opensearch/performanceanalyzer/collectors/HeapMetricsCollectorGCTypesTest.java

Signed-off-by: Filip Drobnjakovic <drobnjakovicfilip@gmail.com>
#286 
By checking the `metricsdb_*` sqlite table (`Heap_Max`) manually it can be seen that both `Eden` and `Survivor` (the two types appearing in issue description) rows are missing and thus never being parsed and causing exceptions.
The roots of the problem go back to collector having hardcoded memory pool name sets when comparing to `MemoryMXBean`'s results. Collector then gets incomplete list of GCTypes and proceeds to emit them to tmp files that later end up as incomplete sql tables.
I added the new possible memory pool names that were missing so now collector succeeds in …

Fix GC types not being collected.

---

src/main/java/org/opensearch/performanceanalyzer/jvm/GarbageCollectorInfo.java

https://github.com/opensearch-project/performance-analyzer-rca/issues/286
- Plugin writes GC info which is read by RCA and dumped into metricsDB. New memory pools were introduced which needs to be handled. This change is for that. 
- Adding new memory pool type
**Additional context - Testing**
- Tested by spinning up a opensearch cluster. 
- Before fix, plugin was writing below in tempfs
```
^gc_info
{"current_time":1677621728046}
{"MemoryPool":"OldGen","CollectorName":"G1 Young Generation"}
{"MemoryPool":"G1 …
```

Fixing issue where GC type metrics are broken

---

.github/CODEOWNERS
MAINTAINERS.md

Fixes https://github.com/opensearch-project/performance-analyzer-rca/issues/293

Baseline MAINTAINERS, CODEOWNERS

---

config/log4j2.xml

Related to PA log bloating issue - https://github.com/opensearch-project/performance-analyzer/issues/226
Also need to change `performance-analyzer.log` to `PerformanceAnalyzer.log` [here](https://github.com/search?q=org%3Aopensearch-project+performance-analyzer.log&type=code)
Move PA log out of `/tmp` to `${sys:opensearch.path.home}/logs/PerformanceAnalyzer.log`. `/usr/share/opensearch/logs/` in most cases.
```
[root@1dbf5d5a3f52 opensearch]# pwd
/usr/share/opensearch
[root@1dbf5d5a3f52 opensearch]# ls logs/
PerformanceAnalyzer.log  gc.log  gc.log.00  performance_analyzer_agent_stats.log
[root@1dbf5d5a3f52 opensearch]# ls /tmp/ …
```

Move PA log from /tmp

---

build.gradle

Introduction of new protobuf version with [change on core](https://github.com/opensearch-project/OpenSearch/pull/7272), broke PA installation with `JarHell` exception. Making this dependency match one from core prevents this from happening again.

Introduce protobuf dependency from core versions file.

---

INSTALL.md
build.gradle
docker/Dockerfile
gradle.properties
src/main/java/org/opensearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotNodeSummary.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/metric/AggregateMetric.java
src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerAppTest.java

Addressing the build failure due to `gradle `version upgrade. From https://github.com/opensearch-project/performance-analyzer-rca/actions/runs/4833884278/jobs/8815180043: 
```
* What went wrong:
A problem was found with the configuration of task ':clonePaGitRepo' (type 'GitClone').
- Type 'org.ajoberstar.gradle.git.tasks.GitClone' property 'authentication' is missing an input or output annotation.
Reason: A property without annotation isn't considered during up-to-date checking.
```
Removing the redundant git clone and replacing with pulling Snapshots from Maven Snapshot repo(https://aws.oss.sonatype.org/content/repositories/snapshots). Refer: …

Updating the PA zip creation logic for docker build

---

src/main/java/org/opensearch/performanceanalyzer/rca/RcaController.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/RcaGraphMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/RcaRuntimeMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java
src/main/java/org/opensearch/performanceanalyzer/reader/MetricsEmitter.java
src/main/java/org/opensearch/performanceanalyzer/reader/ReaderMetricsProcessor.java
src/main/java/org/opensearch/performanceanalyzer/rest/QueryBatchRequestHandler.java
src/test/java/org/opensearch/performanceanalyzer/rca/stats/measurements/MeasurementSetTestHelper.java
src/test/java/org/opensearch/performanceanalyzer/reader/ReaderMetricsProcessorTests.java

https://github.com/opensearch-project/performance-analyzer-rca/issues/363
* Adding Latency metrics for *emission* operation all the metric buckets
* Minor refactoring of different operations metric catgories
Tested by spinning up a docker container on local (`./gradlew runDocker`):
```
etrics=ClusterManagerThrottlingEmitterExecutionTime=13.0 millis aggr|MEAN,ClusterManagerThrottlingEmitterExecutionTime=299 millis aggr|SUM,ClusterManagerThrottlingEmitterExecutionTime=57 millis aggr|MAX,
ThreadNameMetricsEmitterExecutionTime=44 millis aggr|SUM,ThreadNameMetricsEmitterExecutionTime=2.0 millis aggr|MEAN,ThreadNameMetricsEmitterExecutionTime=9 millis …
```

Add Latency Metrics for respective Emitters in Reader Event Processing

---

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerApp.java
src/main/java/org/opensearch/performanceanalyzer/collectors/DisksCollector.java
src/main/java/org/opensearch/performanceanalyzer/collectors/GCInfoCollector.java
src/main/java/org/opensearch/performanceanalyzer/collectors/HeapMetricsCollector.java
src/main/java/org/opensearch/performanceanalyzer/collectors/NetworkInterfaceCollector.java
src/main/java/org/opensearch/performanceanalyzer/collectors/OSMetricsCollector.java
src/main/java/org/opensearch/performanceanalyzer/collectors/ScheduledMetricCollectorsExecutor.java
src/main/java/org/opensearch/performanceanalyzer/jvm/ThreadList.java
src/main/java/org/opensearch/performanceanalyzer/metrics/PerformanceAnalyzerMetrics.java
src/main/java/org/opensearch/performanceanalyzer/net/GRPCConnectionManager.java
src/main/java/org/opensearch/performanceanalyzer/net/NetServer.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ExceptionsAndErrors.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/ReaderMetrics.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/metrics/WriterMetrics.java
src/main/java/org/opensearch/performanceanalyzer/reader/OSEventProcessor.java
src/main/java/org/opensearch/performanceanalyzer/reader/ReaderMetricsProcessor.java
src/main/java/org/opensearch/performanceanalyzer/reader_writer_shared/EventLogFileHandler.java
src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerAppTest.java
src/test/java/org/opensearch/performanceanalyzer/jvm/ThreadListTest.java

[Collector latency metrics](https://github.com/opensearch-project/performance-analyzer-rca/issues/363)
* Adding Collector Metrics and refactoring the Error metrics
* Plugging Writer metrics in collectors. Also added metrics for `COLLECTORS_SLOW` and `COLLECTORS_SKIPPED` collector in scheduler to help identify lagging collectors.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#devel …

Add Collector Service Metrics

---

INSTALL.md
build.gradle
docker/docker-compose.yml

Version bump on 2.x to 2.8

---

.github/workflows/gradle.yml

Build failure see on the main branch due to SHA update for PA-Commons repo
```
Execution failed for task ':dependencyLicenses'.
> SHA has changed! Expected 055767b20346a5db502354b93b199f4d8aad19d7 for performance-analyzer-commons-1.0.0-SNAPSHOT.jar but got c5e251c139d5c635bc24c6d5d12ff9508faa3174.
This usually indicates a corrupt dependency cache or artifacts changed upstream.
Either wipe your cache, fix the upstream artifact, or delete /home/runner/work/performance-analyzer-rca/performance-analyzer-rca/tmp/performance-analyzer/licenses/performance-analyzer-commons-1.0.0-SNAPSHOT.jar.sha1 and run updateShas
```
Add SHA update to gradle.yml …

Add SHA update for PA-Commons to gradle.yml

---

.github/workflows/gradle.yml
build.gradle

Side-effect of https://github.com/opensearch-project/OpenSearch/pull/7604, this is causing JAR Hell when spinning up cluster with RCA present. 
```
> Task :paBwcCluster#oldVersionClusterTask1 FAILED
Exec output and error:
| Output for ./bin/opensearch-plugin:-> Installing file:/Users/khushbr/.gradle/caches/modules-2/files-2.1/org.opensearch.plugin/performance-analyzer/2.8.0.0-SNAPSHOT/d2825b5a621d43f484f5028e9f31078ef0768270/performance-analyzer-2.8.0.0-SNAPSHOT.zip
| -> Downloading file:/Users/khushbr/.gradle/caches/modules-2/files-2.1/org.opensearch.plugin/performance-analyzer/2.8.0.0-SNAPSHOT/d2825b5a621d43f484f5028e9f31078ef0768270/performance-analyzer-2.8.0.0-SNAPSHOT.zip
| -> Failed …
```

Use org.jboss.spec.javax.annotation from core in place of javax.annotation

---

build.gradle

https://github.com/opensearch-project/OpenSearch/pull/7604 has not been backported to 2.8 yet, and thus, it is causing the 2.8 dist PA build to break. This change addresses the failure. 
```
Could not determine the dependencies of task ':distTar'.
> Could not resolve all task dependencies for configuration ':runtimeClasspath'.
> Could not find org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:null.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/null/jboss-annotations-api_1.2_spec-null.pom
- file:/usr/share/opensearch/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2 …
```

Revert Javax annotations dependency from core

---

build.gradle

Due to [PR on core](https://github.com/opensearch-project/OpenSearch/pull/7836).

Swap jboss annotation dependency for jakarta annotations

---

config/rca.conf
config/rca_cluster_manager.conf
config/rca_idle_cluster_manager.conf
src/main/java/org/opensearch/performanceanalyzer/rca/configs/HotShardClusterRcaConfig.java
src/main/java/org/opensearch/performanceanalyzer/rca/configs/HotShardRcaConfig.java
src/main/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotShardSummary.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hotshard/HotShardClusterRca.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/rca/hotshard/HotShardRca.java
src/main/proto/inter_node_rpc_service.proto
src/test/java/org/opensearch/performanceanalyzer/rca/framework/api/RcaTestHelper.java
src/test/java/org/opensearch/performanceanalyzer/rca/framework/api/summaries/HotShardSummaryTest.java
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/cache_tuning/resource/rca.conf
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/collator/resources/rca.conf
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/collator/resources/rca_cluster_manager.conf
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/jvmsizing/resources/rca.conf
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/jvmsizing/resources/rca_cluster_manager.conf
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/jvmsizing/resources/rca_cluster_manager_high_threshold.conf
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/jvmsizing/resources/rca_high_threshold.conf
src/test/java/org/opensearch/performanceanalyzer/rca/integTests/tests/queue_tuning/resource/rca.conf
src/test/java/org/opensearch/performanceanalyzer/rca/store/ResourceHeatMapGraphTest.java
src/test/java/org/opensearch/performanceanalyzer/store/rca/hotshard/HotShardClusterRcaTest.java
src/test/java/org/opensearch/performanceanalyzer/store/rca/hotshard/HotShardRcaTest.java
src/test/resources/rca/rca.conf
src/test/resources/rca/rca_cluster_manager.conf
src/test/resources/rca/rca_elected_cluster_manager.conf
src/test/resources/rca/young_gen/rca.conf
src/test/resources/rca/young_gen/rca_cluster_manager.conf
src/test/resources/rca/young_gen/rca_cluster_manager_high_threshold.conf
src/test/resources/rca/young_gen/rca_high_threshold.conf

Remove HeapAlloc_rate as HotShardRCA's upstream node.

---

src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java

Currently ThreadMetricsRca exectes in 12 seconds instead of 5 seconds. We will need to pass EVALUATION_INTERVAL_SECONDS in the ThreadMetrcisRca constructor instead of RCA_PERIOD
For more information on following Developer Certificate of Origin and …

Set evaluation period from 12 seconds to 5 seconds

---

build.gradle
docker/Dockerfile

According to the naming convention for plugin files, `opensearch-` prefix is kept for the build name and Dockerfile is updated to match that. #413 .

Update plugin artifact name in Dockerfile

---

build.gradle

We recently upgraded the version of spotbug package in https://github.com/opensearch-project/performance-analyzer-rca/pull/405 for RCA 1.3 branch. However the new spotbug package introduced a bunch of new warnings and caused the build to fail. Since in other version branches we are are currently supressing failures, we need to do the same for 1.3 branch to unblock the build and re-enable this flag once we fixed these issues.
By submitting this pull request, I …

set spotbugs ignoreFailures to true

---

build.gradle

This PR resolves the first action item in https://github.com/opensearch-project/performance-analyzer-rca/issues/432, to use mavenLocal as the first entry in repositories section, to ensure that when core/min dependencies are published to maven local, gradle looks at maven local first and gets the required core/min dependencies rather than fetching from snapshots or maven central resulting in false checks.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-r …

use mavenLocal as the first entry in repositories section

---

build.gradle

Currently a lot of unit tests are failing with error:
```
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.Mockito
```
We need to fix the `mockito-core` version to 2.23.0.
reference: https://github.com/mockito/mockito/issues/2568 …

fixing Mockito initialization issue

---

docker/docker-compose.yml

Remove usage of deprecated "master" terminology for 2.x

Remove usage of deprecated "master" terminology for 2.x

---

build.gradle

CVE-2023-32732 - gRPC connection termination issue on grpc-protobuf package versions lower than 1.52
Bumped up gRPC package version to 1.56
-

[CVE-2023-32732] Upgrade gRPC protobug to mitigate connection termincation issue

---

.github/workflows/gradle.yml
INSTALL.md
build.gradle
docker/docker-compose.yml
src/main/java/org/opensearch/performanceanalyzer/rca/Version.java
src/main/java/org/opensearch/performanceanalyzer/rca/store/OpenSearchAnalysisGraph.java

Add changes for release v2.10

---

.github/workflows/gradle.yml

Handle string split on branch ref in gradle.yml. Without quotes, the string was getting split, leading to a branch reference as `2.1.0` instead of `2.10`
```
Execution failed for task ':updateShas'.
> Could not resolve all files for configuration ':runtimeClasspath'.
> Could not find org.opensearch:performanceanalyzer-rca:2.1.0.0-SNAPSHOT.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/org/opensearch/performanceanalyzer-rca/2.1.0.0-SNAPSHOT/maven-metadata.xml
- https://repo.maven.apache.org/maven2/org/opensearch/performanceanalyzer-rca/2.1.0.0-SNAPSHOT/performanceanalyzer-rca-2.1.0.0-SNAPSHOT.pom
- file:/home/runner/.m2/repository/org/opensearch/performanceanalyzer-rca/2.1.0.0-SNAPSHOT/maven-metadata.xml
> Task :updateShas FAILED
- …
```

Handle string split on branch ref in gradle.yml

---

build.gradle
src/main/java/org/opensearch/performanceanalyzer/decisionmaker/deciders/CacheHealthDecider.java

CVE fixes for v1.3.13 release, upgrade the grpc protobuf and netty dependency to `1.56.0`

CVE fixes for v1.3.13 release 

---

build.gradle
src/main/java/org/opensearch/performanceanalyzer/rca/persistence/SQLitePersistor.java
src/main/java/org/opensearch/performanceanalyzer/reader/MetricsEmitter.java
src/test/java/org/opensearch/performanceanalyzer/reader/MetricsEmitterTests.java

https://github.com/opensearch-project/performance-analyzer-rca/issues/492
1. Update Jooq version to `3.16.20`, compatible with sqlite version 
2. Fix error in AdmissionControl Emitter (`AdmissionControl_RejectionCount` configured with 5 columns but the AD Emitter code attempts to bind 6 values, causing failure)
3. Jooq version upgrade related changes 
Tested within RCA Docker container, No more `org.jooq.tools.JooqLogger info INFO: Single batch             : No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse` present in `[root@d47462e53343 logs]# cat PerformanceAnalyzer.log  | …

Update Jooq version and address bind variable failure in AdmissionControl Emitter

---

.github/workflows/gradle.yml
build.gradle

Addresses build failure seen for 2.11.1: https://github.com/opensearch-project/performance-analyzer-rca/actions/runs/6899471514/job/18771262101#step:11:33
```
Execution failed for task ':updateShas'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
> Conflict(s) found for the following module(s):
- org.apache.logging.log4j:log4j-api between versions 2.21.0 and 2.20.0
- org.apache.logging.log4j:log4j-core between versions 2.21.0 and 2.20.0
Run with:
--scan or
:dependencyInsight --configuration runtimeClasspath --dependency org.apache.logging.log4j:log4j-api
to …
```

Update build.gradle to use isSnapshot logic

---

.github/CODEOWNERS
MAINTAINERS.md
build.gradle

Back-porting https://github.com/opensearch-project/performance-analyzer-rca/pull/522 to 2.x

[Backport 2.x] Add new maintainers to repo

---

INSTALL.md
docker/docker-compose.cluster.yml
docker/docker-entrypoint.sh

There were recent changes to security demo configuration setup which now requires a custom admin Password to be setup. This PR updates the documentation and related code change.

Refactors changes related to demo configuration

---

build.gradle

Bumping bouncycastle to v1.78. 
Resolves https://github.com/advisories/GHSA-m44j-cfrm-g8qc, https://github.com/advisories/GHSA-v435-xc8x-wvr9 and https://github.com/advisories/GHSA-8xfc-gm6g-vgpv.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/CONTRIBUTING.md#developer-c …

Bumping bouncycastle to v1.78

---

build.gradle

Coming from https://build.ci.opensearch.org/job/docker-scan/3648/artifact/scan_docker_image.txt, fix the CVE's for 2.16.0 release. Using the version of `bcprov-jdk15to18` and `bcpkix-jdk15to18` from [main branch](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/build.gradle#L359C38-L359C54).
Part of https://github.com/opensearch-project/opensearch-build/issues/4771
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-anal …

[Release 2.16.0] CVE fixes
